import React, { useMemo, useState } from 'react';
import { Helmet } from 'react-helmet-async';

const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v||0);
const items=[
 {id:'a',section:'17(5)(a)',name:'Motor vehicle / conveyance',note:'ITC is restricted for specified motor vehicles/conveyances, subject to statutory exceptions such as further supply, passenger transportation, or training.'},
 {id:'b',section:'17(5)(ab)',name:'Insurance / servicing / repair / maintenance of blocked vehicles or vessels/aircraft',note:'Credit can follow the statutory exceptions, including where the underlying asset is used for an eligible purpose or the inward supply is used for further supply of the same category.'},
 {id:'c',section:'17(5)(b)',name:'Food, beverages, outdoor catering and specified personal services',note:'Generally blocked, subject to specified exceptions such as making an outward taxable supply of the same category or statutory obligations.'},
 {id:'d',section:'17(5)(c)',name:'Works contract for construction of immovable property',note:'Blocked where the works contract service is used for construction of an immovable property, other than plant and machinery, except where it is an input service for further supply of works contract service.'},
 {id:'e',section:'17(5)(d)',name:'Goods/services for construction of immovable property on own account',note:'Blocked when used for construction on own account, even when used in the course or furtherance of business; plant and machinery is treated separately under the statutory definition.'},
 {id:'f',section:'17(5)(e)',name:'Supplies taxed under composition scheme',note:'ITC is not available on goods or services on which tax has been paid under section 10.'},
 {id:'g',section:'17(5)(f)',name:'Supplies received by a non-resident taxable person',note:'Blocked except for goods imported by the non-resident taxable person.'},
 {id:'h',section:'17(5)(fa)',name:'CSR expenditure',note:'ITC on goods or services or both received for activities relating to obligations under section 135 of the Companies Act is blocked.'},
 {id:'i',section:'17(5)(g)',name:'Personal consumption',note:'ITC is blocked to the extent goods or services are used for personal consumption.'},
 {id:'j',section:'17(5)(h)',name:'Lost, stolen, destroyed, written off, gifts and free samples',note:'ITC is blocked to the extent of goods lost, stolen, destroyed, written off or disposed of by way of gift or free samples.'},
 {id:'k',section:'17(5)(i)',name:'Tax paid under specified demand provisions',note:'ITC is blocked for tax paid pursuant to specified demand provisions under the CGST Act, including the provisions referred to in section 17(5)(i).'}
];
export default function GSTBlockedITCPage(){
 const [category,setCategory]=useState('all'); const [amount,setAmount]=useState(''); const [selected,setSelected]=useState('c');
 const result=useMemo(()=>items.find(x=>x.id===selected)||items[0],[selected]);
 return <><Helmet><title>GST Blocked ITC Calculator | Section 17(5) CGST Act</title><meta name="description" content="GST blocked input tax credit decision tool covering section 17(5) CGST Act categories, common exceptions and indicative ineligible ITC."/><link rel="canonical" href="https://www.cssiddhijain.com/calculators/gst-blocked-itc"/></Helmet>
 <main className="min-h-screen bg-slate-50 py-10 px-4"><div className="max-w-6xl mx-auto"><p className="text-sm font-semibold text-teal-700 uppercase tracking-wide">GST Technical Tool</p><h1 className="text-3xl md:text-4xl font-bold text-gray-900 mt-2">Blocked ITC — Section 17(5)</h1><p className="text-gray-600 mt-3 max-w-4xl">Select the nature of the expenditure and see the relevant blocked-credit provision, common statutory exceptions and an indicative amount of ITC that may be ineligible.</p>
 <div className="grid lg:grid-cols-5 gap-6 mt-8"><section className="lg:col-span-3 bg-white rounded-2xl border border-gray-200 p-6 md:p-8"><div className="grid md:grid-cols-2 gap-5">
 <div><label className="block text-sm font-semibold text-gray-700 mb-2">Expenditure category</label><select className="w-full rounded-xl border border-gray-200 px-4 py-3" value={selected} onChange={e=>setSelected(e.target.value)}>{items.map(x=><option key={x.id} value={x.id}>{x.section} — {x.name}</option>)}</select></div>
 <div><label className="block text-sm font-semibold text-gray-700 mb-2">GST amount / ITC under review (₹)</label><input className="w-full rounded-xl border border-gray-200 px-4 py-3" type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="e.g. 18000"/></div>
 </div><div className="mt-7 rounded-2xl bg-slate-50 border border-gray-100 p-5"><div className="text-sm text-gray-500">Selected provision</div><h2 className="text-xl font-bold text-gray-900 mt-1">{result.section} — {result.name}</h2><p className="text-gray-600 mt-3 leading-relaxed">{result.note}</p></div>
 <div className="mt-6 grid md:grid-cols-3 gap-3">{[['17(5)(a)','Vehicles'],['17(5)(b)','Food / services'],['17(5)(c)/(d)','Construction'],['17(5)(fa)','CSR'],['17(5)(g)','Personal'],['17(5)(h)','Loss / gifts']].map(([v,l])=><button type="button" key={v} onClick={()=>{const x=items.find(i=>i.section===v)||items.find(i=>i.section.startsWith(v.split('/')[0]));if(x)setSelected(x.id)}} className="text-left rounded-xl border border-gray-200 p-3 hover:border-teal-300"><div className="text-xs font-bold text-teal-700">{v}</div><div className="text-sm text-gray-700 mt-1">{l}</div></button>)}</div>
 </section>
 <section className="lg:col-span-2 bg-slate-900 text-white rounded-2xl p-6 md:p-8"><p className="text-sm text-slate-300">Indicative blocked ITC</p><div className="text-4xl font-bold mt-2">{money(Number(amount)||0)}</div><p className="text-sm text-slate-300 mt-2">Subject to the exact exception and use test.</p><div className="border-t border-slate-700 my-6"/><div className="text-sm"><div className="text-slate-400">Rule</div><div className="font-semibold mt-1">{result.section}</div><div className="text-slate-300 mt-4 leading-relaxed">{result.note}</div></div></section></div>
 <div className="mt-6 bg-white border border-gray-200 rounded-2xl p-5 text-sm text-gray-600 leading-relaxed"><strong className="text-gray-800">Important:</strong> Section 17(5) is exception-driven. This tool flags the relevant blocked-credit category; it does not determine ITC eligibility without checking business use, outward supply, employee/employer relationship, statutory obligation, plant and machinery, notifications and other conditions. CBIC materials identify section 17(5) as the negative list for blocked credit.</div>
 </div></main></>;
}
